In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_excel('Urls.xlsx')
df

,index,urls,Story_Text,Pledge_Text,Story_Score,Pledge_Score,Comments,Updates,Created,Backed,Story_Word_Count,Pledge_Word_Count
0,0,https://www.kickstarter.com/projects/atnightif...,The Story_x000D_\nA podcast that only starts i...,The Pledge US$ 1 or more_x000D_\nStandard Good...,9.99,11.16,0.0,9.0,A First created_x000D_\n·_x000D_\n2 backed,NaN,1553.0,670.0
1,1,https://www.kickstarter.com/projects/saasgrave...,The Story_x000D_\nWe have launched a podcast a...,The Pledge US$ 1 or more_x000D_\nOnline Shout ...,11.21,16.11,0.0,3.0,A First created_x000D_\n·_x000D_\n0 backed,NaN,111.0,200.0
2,2,https://www.kickstarter.com/projects/gottsnack...,The Story_x000D_\nMy name is Fredrik Söderholm...,The Pledge SEK 300 or more_x000D_\nPrank call ...,10.63,11.66,0.0,0.0,A 2 created_x000D_\n·_x000D_\n1 backed,NaN,957.0,820.0
3,3,https://www.kickstarter.com/projects/barkercas...,The Story_x000D_\nHi! If you're here you're ho...,The Pledge US$ 1 or more_x000D_\nThanks On The...,9.68,17.59,2.0,5.0,A 7 created_x000D_\n·_x000D_\n11 backed,NaN,237.0,1205.0
4,4,https://www.kickstarter.com/projects/zine-issu...,The Story_x000D_\nMy name is Samuel de Broize-...,The Pledge £5 or more_x000D_\nJOIN THE FAMILY_...,11.5,14.66,1.0,2.0,A 3 created_x000D_\n·_x000D_\n0 backed,NaN,901.0,884.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,https://www.kickstarter.com/projects/billba/un...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49996,49996,https://www.kickstarter.com/projects/j-nelson/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49997,49997,https://www.kickstarter.com/projects/arischind...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49998,49998,https://www.kickstarter.com/projects/62860951/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49999,49999,https://www.kickstarter.com/projects/176308374...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_new = df['Created'][:500]
df_new

0      A  First created_x000D_\n·_x000D_\n2 backed
1      A  First created_x000D_\n·_x000D_\n0 backed
2          A  2 created_x000D_\n·_x000D_\n1 backed
3         A  7 created_x000D_\n·_x000D_\n11 backed
4          A  3 created_x000D_\n·_x000D_\n0 backed
                          ...
495    A  First created_x000D_\n·_x000D_\n1 backed
496       A  2 created_x000D_\n·_x000D_\n42 backed
497    A  First created_x000D_\n·_x000D_\n3 backed
498    A  First created_x000D_\n·_x000D_\n3 backed
499     A  10 created_x000D_\n·_x000D_\n346 backed
Name: Created, Length: 500, dtype: object

In [ ]:
Created = []
Backed = []
for val in range(df_new.shape[0]):
    text = df_new[val].replace("_x000D_\n","")
    temp = re.findall(r'\d+', str)
    Backed.append(temp[-1])