In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import *

#Load sklearn
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.preprocessing import MinMaxScaler

# Import Classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
import xgboost

In [2]:
df = pd.read_csv('Final Data.csv')
df

,backers_count,country,created_at,deadline,fx_rate,goal,launched_at,spotlight,staff_pick,state_changed_at,class,Score,Comments,Updates
0,45,US,1577743896,1581179226,1.000000,4500.0,1578328026,True,True,1581179226,1,10.47,0.0,9.0
1,21,US,1573666016,1578252537,1.000000,300.0,1575660537,True,False,1578252537,1,14.33,0.0,3.0
2,146,SE,1574880653,1577905200,0.116116,50000.0,1575459486,True,False,1577905200,1,11.18,0.0,0.0
3,31,US,1574060612,1576664821,1.000000,500.0,1574072821,True,False,1576664821,1,15.96,2.0,4.0
4,9,GB,1571141508,1576414740,1.380491,250.0,1573500464,True,False,1576414740,1,12.80,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64713,51,US,1418766416,1425868872,1.000000,5000.0,1423280472,True,False,1425868872,1,13.92,9.0,7.0
64714,11,US,1493913962,1497110947,1.000000,60000.0,1494518947,False,False,1497110948,0,16.24,1.0,0.0
64715,18,US,1427324752,1427677200,1.000000,850.0,1427418491,True,False,1427677215,1,13.46,1.0,4.0
64716,1,GB,1398336316,1401044620,1.406145,10000.0,1398452620,False,False,1401044620,0,13.33,0.0,1.0
64717,46,US,1616348731,1619378474,1.000000,300.0,1616786474,True,False,1619378474,1,13.79,6.0,1.0

In [3]:
df['fund_goal'] = df['fx_rate']*df['goal']
df.drop(['spotlight','backers_count','country','state_changed_at','fx_rate','goal'], axis = 1, inplace =True)
df

,created_at,deadline,launched_at,staff_pick,class,Score,Comments,Updates,fund_goal
0,1577743896,1581179226,1578328026,True,1,10.47,0.0,9.0,4500.000000
1,1573666016,1578252537,1575660537,False,1,14.33,0.0,3.0,300.000000
2,1574880653,1577905200,1575459486,False,1,11.18,0.0,0.0,5805.824500
3,1574060612,1576664821,1574072821,False,1,15.96,2.0,4.0,500.000000
4,1571141508,1576414740,1573500464,False,1,12.80,1.0,2.0,345.122725
...,...,...,...,...,...,...,...,...,...
64713,1418766416,1425868872,1423280472,False,1,13.92,9.0,7.0,5000.000000
64714,1493913962,1497110947,1494518947,False,0,16.24,1.0,0.0,60000.000000
64715,1427324752,1427677200,1427418491,False,1,13.46,1.0,4.0,850.000000
64716,1398336316,1401044620,1398452620,False,0,13.33,0.0,1.0,14061.454200
64717,1616348731,1619378474,1616786474,False,1,13.79,6.0,1.0,300.000000

In [4]:
df_new = pd.get_dummies(df, columns=['staff_pick'],drop_first=True)
df_new

,created_at,deadline,launched_at,class,Score,Comments,Updates,fund_goal,staff_pick_True
0,1577743896,1581179226,1578328026,1,10.47,0.0,9.0,4500.000000,1
1,1573666016,1578252537,1575660537,1,14.33,0.0,3.0,300.000000,0
2,1574880653,1577905200,1575459486,1,11.18,0.0,0.0,5805.824500,0
3,1574060612,1576664821,1574072821,1,15.96,2.0,4.0,500.000000,0
4,1571141508,1576414740,1573500464,1,12.80,1.0,2.0,345.122725,0
...,...,...,...,...,...,...,...,...,...
64713,1418766416,1425868872,1423280472,1,13.92,9.0,7.0,5000.000000,0
64714,1493913962,1497110947,1494518947,0,16.24,1.0,0.0,60000.000000,0
64715,1427324752,1427677200,1427418491,1,13.46,1.0,4.0,850.000000,0
64716,1398336316,1401044620,1398452620,0,13.33,0.0,1.0,14061.454200,0
64717,1616348731,1619378474,1616786474,1,13.79,6.0,1.0,300.000000,0

In [94]:
df_input_old = df_new[['Updates']]
df_ouput = df_new['class']

In [95]:
df_input_old = np.reshape(df_input_old, (-1,1))
df_input_old

       Updates
0          9.0
1          3.0
2          0.0
3          4.0
4          2.0
...        ...
64713      7.0
64714      0.0
64715      4.0
64716      1.0
64717      1.0

[64718 rows x 1 columns]

In [96]:
df_ouput

0        1
1        1
2        1
3        1
4        1
        ..
64713    1
64714    0
64715    1
64716    0
64717    1
Name: class, Length: 64718, dtype: int64

In [97]:
X_train, X_test, y_train, y_test = train_test_split(df_input_old, df_ouput, test_size=0.3,random_state=158)

### Logistic Regression

In [98]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8083024309847548
Precision :  0.8979434199092401
Recall :  0.7772670288340995
F1 Score :  0.8332586685780844
AUC :  0.8177034379172511

### RandomForest

In [99]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.824835187474248
Precision :  0.8708643686125065
Recall :  0.8403677392394484
F1 Score :  0.855344306920165
AUC :  0.8201301855504717

### AdaBoost

In [100]:
model = AdaBoostClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.824835187474248
Precision :  0.8708643686125065
Recall :  0.8403677392394484
F1 Score :  0.855344306920165
AUC :  0.8201301855504717

### Gradient AdaBoost

In [101]:
model = GradientBoostingClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.824835187474248
Precision :  0.8708643686125065
Recall :  0.8403677392394484
F1 Score :  0.855344306920165
AUC :  0.8201301855504717

### Xtreme Gradient Adaboost

In [102]:
model = xgboost.XGBClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

[17:06:22] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\acer\AppData\Roaming\Python\Python310\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Accuracy :  0.824835187474248
Precision :  0.8708643686125065
Recall :  0.8403677392394484
F1 Score :  0.855344306920165
AUC :  0.8201301855504717

### Perceptron

In [103]:
model = Perceptron()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.8144829007004533
Precision :  0.8124486288575058
Recall :  0.9087338069368993
F1 Score :  0.857898059018463
AUC :  0.7859331361888897

### Support Vector Machine

In [104]:
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.824835187474248
Precision :  0.8708643686125065
Recall :  0.8403677392394484
F1 Score :  0.855344306920165
AUC :  0.8201301855504717

### Gaussian Naive Bayes

In [105]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy : " , accuracy_score(y_test,y_pred))
print("Precision : " , precision_score(y_test,y_pred))
print("Recall : " , recall_score(y_test,y_pred))
print("F1 Score : " , f1_score(y_test,y_pred))
print("AUC : " , roc_auc_score(y_test,y_pred))

Accuracy :  0.7297589616810878
Precision :  0.940582371458552
Recall :  0.5993313832010029
F1 Score :  0.7321455919138291
AUC :  0.769267087386302